version: '3'

services:
  api:
    image: victor141516/calendaring
    build: .
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "3000:3000"

  redis:
    image: "redis:alpine"
    volumes:
      - ./cache:/data
    command: redis-server --appendonly yes
